SteelMeltingMixtureApp/Controllers/ComponentsController.cs
using SteelMeltingMixture.Domain;
using SteelMeltingMixtureApp.Infrastructure;
using SteelMeltingMixtureApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SteelMeltingMixtureApp.Controllers
{
    [Authorize] // К контроллеру получают доступ только аутентифицированные пользователи.
    public class ComponentsController : Controller
    {
        // Dependency Injection
        // Данные поля будут хранит ссылки на реальные репозитории или на тестовые в соответствии с параметрами переданными в конструктор
        IComponentsRepository _components;
        IUserProfileRepository _users;

        
        public ComponentsController()
            : this(new DALContext())
        {
        }

        
        public ComponentsController(IDALContext context)
        {
            _components = context.Components;
            _users = context.Users;
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            SteelMeltingMixtureDatabase _database = new SteelMeltingMixtureDatabase();
            _database.Components.RemoveRange(_database.Components.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(Components components)
        {
            #region --- Ввод тестовых данных в базу данных

            Components component_1 = new Components { NameComponent = "Чугун литейный хромоникелевый", Cost = 75.5, MinValComponent = 45.0, MaxValComponent = 75.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_1);
            _components.Save();

            Components component_2 = new Components { NameComponent = "Чугун литейный коксовый", Cost = 68.0, MinValComponent = 0.0, MaxValComponent = 100.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_2);
            _components.Save();

            Components component_3 = new Components { NameComponent = "Чугун зеркальный", Cost = 97.0, MinValComponent = 10.0, MaxValComponent = 20.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_3);
            _components.Save();

            Components component_4 = new Components { NameComponent = "Лом чугунный", Cost = 36.2, MinValComponent = 6.0, MaxValComponent = 15.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_4);
            _components.Save();

            Components component_5 = new Components { NameComponent = "Лом стальной", Cost = 34.3, MinValComponent = 6.0, MaxValComponent = 15.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_5);
            _components.Save();

            Components component_6 = new Components { NameComponent = "Возврат", Cost = 36.2, MinValComponent = 12.0, MaxValComponent = 40.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_6);
            _components.Save();

            Components component_7 = new Components { NameComponent = "Ферромарганец", Cost = 120.0, MinValComponent = 0.0, MaxValComponent = 100.0, IsSolve = true, Owner = _users.CurrentUser };
            _components.InsertOrUpdate(component_7);
            _components.Save();

            #endregion --- Ввод тестовых данных в базу данных

            return RedirectToAction("Index");
        }


        //
        // GET: /Components/

        public ActionResult Index()
        {
            return View(_users.CurrentUser.Components.ToList());
           
        }

        //
        // GET: /Components/Create

        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Components/
        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Create(Components components)
        {
            if (ModelState.IsValid)
            {
                components.Owner = _users.CurrentUser;
                _components.InsertOrUpdate(components);
                _components.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /Components/Edit/1
        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Edit(int id)
        {
            return View(_components.All.FirstOrDefault(t => t.ID_Component == id));
        }

        //
        // POST: /Components/Edit/

        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Edit(Components components)
        {
            if (ModelState.IsValid)
            {
                _components.InsertOrUpdate(components);
                _components.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // Edit: /Components/Delete/1
        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Delete(int id)
        {
            return View(_components.All.FirstOrDefault(t => t.ID_Component == id));
        }

        //
        // POST: /Components/Delete/1
        /*[Authorize(Roles = "Admin")]*/ // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _components.Remove(_components.All.FirstOrDefault(t => t.ID_Component == id));
            _components.Save();
            return RedirectToAction("Index");
        }
    }
}

SteelMeltingMixtureApp/Controllers/ElementsController.cs
using SteelMeltingMixture.Domain;
using SteelMeltingMixtureApp.Infrastructure;
using SteelMeltingMixtureApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SteelMeltingMixtureApp.Controllers
{
    [Authorize] // К контроллеру получают доступ только аутентифицированные пользователи.
    public class ElementsController : Controller
    {
        // Dependency Injection
        // Данные поля будут хранит ссылки на реальные репозитории или на тестовые в соответствии с параметрами переданными в конструктор
        IElementsRepository _elements;
        IUserProfileRepository _users;

        public ElementsController()
            : this(new DALContext())
        {
        }

        public ElementsController(IDALContext context)
        {
            _elements = context.Elements;
            _users = context.Users;
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            SteelMeltingMixtureDatabase _database = new SteelMeltingMixtureDatabase();
            _database.Elements.RemoveRange(_database.Elements.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(Elements elements)
        {
            #region --- Ввод тестовых данных в базу данных

            Elements element_1 = new Elements { NameElement = "Si", MinValElement = 2.30, MaxValElement = 2.60, IsSolve = true, Owner = _users.CurrentUser };
            _elements.InsertOrUpdate(element_1);
            _elements.Save();

            Elements element_2 = new Elements { NameElement = "Mn", MinValElement = 0.37, MaxValElement = 3.10, IsSolve = true, Owner = _users.CurrentUser };
            _elements.InsertOrUpdate(element_2);
            _elements.Save();

            Elements element_3 = new Elements { NameElement = "Cr", MinValElement = 1.40, MaxValElement = 3.40, IsSolve = true, Owner = _users.CurrentUser };
            _elements.InsertOrUpdate(element_3);
            _elements.Save();

            Elements element_4 = new Elements { NameElement = "Ni", MinValElement = 0.70, MaxValElement = 1.50, IsSolve = true, Owner = _users.CurrentUser };
            _elements.InsertOrUpdate(element_4);
            _elements.Save();

            #endregion --- Ввод тестовых данных в базу данных

            return RedirectToAction("Index");
        }

        //
        // GET: /Elements/

        public ActionResult Index()
        {
            return View(_users.CurrentUser.Elements.ToList());
        }

        //
        // GET: /Elements/Create

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Elements/
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Create(Elements elements)
        {
            if (ModelState.IsValid)
            {
                elements.Owner = _users.CurrentUser;
                _elements.InsertOrUpdate(elements);
                _elements.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /Elements/Edit/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Edit(int id)
        {
            return View(_elements.All.FirstOrDefault(t => t.ID_Element == id));
        }

        //
        // POST: /Elements/Edit/

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Edit(Elements elements)
        {
            if (ModelState.IsValid)
            {
                _elements.InsertOrUpdate(elements);
                _elements.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // Edit: /Elements/Delete/1
        // [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Delete(int id)
        {
            return View(_elements.All.FirstOrDefault(t => t.ID_Element == id));
        }

        //
        // POST: /Elements/Delete/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _elements.Remove(_elements.All.FirstOrDefault(t => t.ID_Element == id));
            _elements.Save();
            return RedirectToAction("Index");
        }
    }
}

SteelMeltingMixtureApp/Controllers/VariantsController.cs
using SteelMeltingMixture.Domain;
using SteelMeltingMixtureApp.Infrastructure;
using SteelMeltingMixtureApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SteelMeltingMixtureApp.Controllers
{
    [Authorize] // К контроллеру получают доступ только аутентифицированные пользователи.
    public class VariantsController : Controller
    {
        // Dependency Injection
        // Данные поля будут хранит ссылки на реальные репозитории или на тестовые в соответствии с параметрами переданными в конструктор
        IVariantsRepository _variants;
        IUserProfileRepository _users;

        public VariantsController()
            : this(new DALContext())
        {
        }

        public VariantsController(IDALContext context)
        {
            _variants = context.Variants;
            _users = context.Users;
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            SteelMeltingMixtureDatabase _database = new SteelMeltingMixtureDatabase();
            _database.Variants.RemoveRange(_database.Variants.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(Variants variants)
        {
            #region --- Ввод тестовых данных в базу данных

            Variants var_1 = new Variants { NameVariant = "Вариант 1", DateVariant = new DateTime (2020, 05, 01), Owner = _users.CurrentUser };
            _variants.InsertOrUpdate(var_1);
            _variants.Save();

            #endregion --- Ввод тестовых данных в базу данных

            return RedirectToAction("Index");
        }

        //
        // GET: /Variants/

        public ActionResult Index()
        {
            return View(_users.CurrentUser.Variants.ToList());
        }

        //
        // GET: /Variants/Create

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Variants/
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Create(Variants variants)
        {
            if (ModelState.IsValid)
            {
                variants.Owner = _users.CurrentUser;
                _variants.InsertOrUpdate(variants);
                _variants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // GET: /Variants/Edit/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Edit(int id)
        {
            return View(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
        }

        //
        // POST: /Variants/Edit/

        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        public ActionResult Edit(Variants variants)
        {
            if (ModelState.IsValid)
            {
                _variants.InsertOrUpdate(variants);
                _variants.Save();
            }
            return RedirectToAction("Index");
        }

        //
        // Edit: /Variants/Delete/1
        // [Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        public ActionResult Delete(int id)
        {
            return View(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
        }

        //
        // POST: /Variants/Delete/1
        //[Authorize(Roles = "Admin")] // К данному методу действия могут получать доступ только пользователи с ролью Admin
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            _variants.Remove(_variants.All.FirstOrDefault(t => t.ID_Variant == id));
            _variants.Save();
            return RedirectToAction("Index");
        }
    }
}

SteelMeltingMixtureApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "Информация о программе";
}
<link rel="stylesheet" href="~/Content/css/bootstrap.css" />
<body>
    <div class="container">
        <div>
            <h2>@ViewBag.Title.</h2>
            <h3>@ViewBag.Message</h3>
        </div>
        <p>
            Авторы: Бабушкин Борис Дмитриевич, Лавров Владислав Васильевич.<br />
            @ViewBag.Assembly<br />
            2020 г.
        </p>
    </div>
</body>

SteelMeltingMixtureApp/Views/Home/Cabinet.cshtml
@{
    ViewBag.Title = "Личный кабинет пользователя";
}
    <link rel="stylesheet" href="~/Content/css/bootstrap.css" />
    <body>
        <div class="container">
            <div class="text-secondary">
                <hgroup class="title">
                    <h1>@ViewBag.Title.</h1>
                </hgroup>
            </div>
            <aside>
                <div class="text-success">
                    <h3>Демонстрационный пример решения задачи</h3>
                    <p>
                        Тестовые данные, расчет и отображение результатов в табличной и графической формах
                    </p>
                    <ul>
                        <li>@Html.ActionLink("Демонстрационный пример", "Demo", "Home")</li>
                        <li>@Html.ActionLink("Выполнить расчет", "Universal", "Home")</li>
                    </ul>
                </div>
            </aside>

            <aside>
                <div class="text-success">
                    @if (User.IsInRole("Admin"))
                    {
                        <h3>Таблицы базы данных</h3>
                        <p>
                            Просмотр и редактирование данных в таблицах
                        </p>
                        <ul>
                            <li>@Html.ActionLink("Справочник вариантов расчета", "Index", "Variants")</li>
                            <li>@Html.ActionLink("Справочник компонентов шихты", "Index", "Components")</li>
                            <li>@Html.ActionLink("Справочник химических элементов", "Index", "Elements")</li>
                            <li>@Html.ActionLink("Состав компонентов шихты", "Index", "ComponentsElements")</li>
                        </ul>
                    }

                    else
                    {

                    }

                </div>
            </aside>
        </div>
    </body>

SteelMeltingMixtureApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}

    <link rel="stylesheet" href="~/Content/css/bootstrap.css" />
<body>
    <div class="container">
        <h2>@ViewBag.Title.</h2>
        <h3>@ViewBag.Message</h3>



        <address>
            620002, Россия, г. Екатеринбург, ул. Мира, д. 28.<br />
            Кафедра "Теплофизика и информатика в металлургии", ИНМиТ Уральский федеральный университет<br />
            <abbr title="Телефон рабочий">Телефон рабочий:</abbr>
            (343) 375-44-51
        </address>



        <address>
            <strong>Техническая поддержка:</strong>   <a href="mailto:v.v.lavrov@urfu.ru">v.v.lavrov@urfu.ru</a><br />

        </address>
    </div>
</body>

SteelMeltingMixtureApp/Views/Home/Demo - Копировать.cshtml
@*@{
    ViewBag.Title = "Демонстрационный пример решения задачи оптимизации сталеплавильной шихты";
}
<br />

<link rel="stylesheet" href="~/Content/css/bootstrap.css" />
<script src="~/Scripts/js/bootstrap.js"></script>

<div class="form-group">
    <label style="font-size: 35px; margin-left: +500px; color: forestgreen" class="col-8">Исходные данные:</label>
    <br />
</div>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Компонент шихты</th>
            <th scope="col">Si</th>
            <th scope="col">Mn</th>
            <th scope="col">Cr</th>
            <th scope="col">Ni</th>
            <th scope="col">Стоимость, у.е./т</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Чугун литейный хромоникелевый</th>
            <td>2,95</td>
            <td>0,55</td>
            <td>




<script type="text/javascript">
    $(document).ready(function () {
        $('#form_calc').on('submit', function (e) {


            var Si_InComponent_1 = parseFloat($('input[name="Si_InComponent_1"]').val().replace(/,/, '.'));
            var Mn_InComponent_1 = parseFloat($('input[name="Mn_InComponent_1"]').val().replace(/,/, '.'));
            var Cr_InComponent_1 = parseFloat($('input[name="Cr_InComponent_1"]').val().replace(/,/, '.'));
            var Ni_InComponent_1 = parseFloat($('input[name="Ni_InComponent_1"]').val().replace(/,/, '.'));
            var CostComponent_1 = parseFloat($('input[name="CostComponent_1"]').val().replace(/,/, '.'));

            var Si_InComponent_2 = parseFloat($('input[name="Si_InComponent_2"]').val().replace(/,/, '.'));
            var Mn_InComponent_2 = parseFloat($('input[name="Mn_InComponent_2"]').val().replace(/,/, '.'));
            var Cr_InComponent_2 = parseFloat($('input[name="Cr_InComponent_2"]').val().replace(/,/, '.'));
            var Ni_InComponent_2 = parseFloat($('input[name="Ni_InComponent_2"]').val().replace(/,/, '.'));
            var CostComponent_2 = parseFloat($('input[name="CostComponent_2"]').val().replace(/,/, '.'));

            var Si_InComponent_3 = parseFloat($('input[name="Si_InComponent_3"]').val().replace(/,/, '.'));
            var Mn_InComponent_3 = parseFloat($('input[name="Mn_InComponent_3"]').val().replace(/,/, '.'));
            var Cr_InComponent_3 = parseFloat($('input[name="Cr_InComponent_3"]').val().replace(/,/, '.'));
            var Ni_InComponent_3 = parseFloat($('input[name="Ni_InComponent_3"]').val().replace(/,/, '.'));
            var CostComponent_3 = parseFloat($('input[name="CostComponent_3"]').val().replace(/,/, '.'));

            var Si_InComponent_4 = parseFloat($('input[name="Si_InComponent_4"]').val().replace(/,/, '.'));
            var Mn_InComponent_4 = parseFloat($('input[name="Mn_InComponent_4"]').val().replace(/,/, '.'));
            var Cr_InComponent_4 = parseFloat($('input[name="Cr_InComponent_4"]').val().replace(/,/, '.'));
            var Ni_InComponent_4 = parseFloat($('input[name="Ni_InComponent_4"]').val().replace(/,/, '.'));
            var CostComponent_4 = parseFloat($('input[name="CostComponent_4"]').val().replace(/,/, '.'));

            var Si_InComponent_5 = parseFloat($('input[name="Si_InComponent_5"]').val().replace(/,/, '.'));
            var Mn_InComponent_5 = parseFloat($('input[name="Mn_InComponent_5"]').val().replace(/,/, '.'));
            var Cr_InComponent_5 = parseFloat($('input[name="Cr_InComponent_5"]').val().replace(/,/, '.'));
            var Ni_InComponent_5 = parseFloat($('input[name="Ni_InComponent_5"]').val().replace(/,/, '.'));
            var CostComponent_5 = parseFloat($('input[name="CostComponent_5"]').val().replace(/,/, '.'));

            var Si_InComponent_6 = parseFloat($('input[name="Si_InComponent_6"]').val().replace(/,/, '.'));
            var Mn_InComponent_6 = parseFloat($('input[name="Mn_InComponent_6"]').val().replace(/,/, '.'));
            var Cr_InComponent_6 = parseFloat($('input[name="Cr_InComponent_6"]').val().replace(/,/, '.'));
            var Ni_InComponent_6 = parseFloat($('input[name="Ni_InComponent_6"]').val().replace(/,/, '.'));
            var CostComponent_6 = parseFloat($('input[name="CostComponent_6"]').val().replace(/,/, '.'));

            var Si_InComponent_7 = parseFloat($('input[name="Si_InComponent_7"]').val().replace(/,/, '.'));
            var Mn_InComponent_7 = parseFloat($('input[name="Mn_InComponent_7"]').val().replace(/,/, '.'));
            var Cr_InComponent_7 = parseFloat($('input[name="Cr_InComponent_7"]').val().replace(/,/, '.'));
            var Ni_InComponent_7 = parseFloat($('input[name="Ni_InComponent_7"]').val().replace(/,/, '.'));
            var CostComponent_7 = parseFloat($('input[name="CostComponent_7"]').val().replace(/,/, '.'));


            var ComponentMin_1 = parseFloat($('input[name="ComponentMin_1"]').val().replace(/,/, '.'));
            var ComponentMax_1 = parseFloat($('input[name="ComponentMax_1"]').val().replace(/,/, '.'));

            var ComponentMin_2 = parseFloat($('input[name="ComponentMin_2"]').val().replace(/,/, '.'));
            var ComponentMax_2 = parseFloat($('input[name="ComponentMax_2"]').val().replace(/,/, '.'));

            var ComponentMin_3 = parseFloat($('input[name="ComponentMin_3"]').val().replace(/,/, '.'));
            var ComponentMax_3 = parseFloat($('input[name="ComponentMax_3"]').val().replace(/,/, '.'));

            var ComponentMin_4 = parseFloat($('input[name="ComponentMin_4"]').val().replace(/,/, '.'));
            var ComponentMax_4 = parseFloat($('input[name="ComponentMax_4"]').val().replace(/,/, '.'));

            var ComponentMin_5 = parseFloat($('input[name="ComponentMin_5"]').val().replace(/,/, '.'));
            var ComponentMax_5 = parseFloat($('input[name="ComponentMax_5"]').val().replace(/,/, '.'));

            var ComponentMin_6 = parseFloat($('input[name="ComponentMin_6"]').val().replace(/,/, '.'));
            var ComponentMax_6 = parseFloat($('input[name="ComponentMax_6"]').val().replace(/,/, '.'));

            var ComponentMin_7 = parseFloat($('input[name="ComponentMin_7"]').val().replace(/,/, '.'));
            var ComponentMax_7 = parseFloat($('input[name="ComponentMax_7"]').val().replace(/,/, '.'));


            var Si_InShihtaNeed_Min = parseFloat($('input[name="Si_InShihtaNeed_Min"]').val().replace(/,/, '.'));
            var Si_InShihtaNeed_Max = parseFloat($('input[name="Si_InShihtaNeed_Max"]').val().replace(/,/, '.'));

            var Mn_InShihtaNeed_Min = parseFloat($('input[name="Mn_InShihtaNeed_Min"]').val().replace(/,/, '.'));
            var Mn_InShihtaNeed_Max = parseFloat($('input[name="Mn_InShihtaNeed_Max"]').val().replace(/,/, '.'));

            var Cr_InShihtaNeed_Min = parseFloat($('input[name="Cr_InShihtaNeed_Min"]').val().replace(/,/, '.'));
            var Cr_InShihtaNeed_Max = parseFloat($('input[name="Cr_InShihtaNeed_Max"]').val().replace(/,/, '.'));

            var Ni_InShihtaNeed_Min = parseFloat($('input[name="Ni_InShihtaNeed_Min"]').val().replace(/,/, '.'));
            var Ni_InShihtaNeed_Max = parseFloat($('input[name="Ni_InShihtaNeed_Max"]').val().replace(/,/, '.'));


            //if ((mass_suh < 1000) || (mass_suh > 100000)) {
            //    alert("Ошибка! Масса сухового материала должна быть в пределах от 1000 до 100000 кг!");
            //    return false;
            //}
            //if ((nach_vlaj < 0.1) || (nach_vlaj > 100)) {
            //    alert("Ошибка! Начальная влажность форм должна быть в пределах от 0,1 до 100 %!");
            //    return false;
            //}
            //if ((kone_vlaj < 0.1) || (kone_vlaj > 100)) {
            //    alert("Ошибка! Конечная влажность форм должна быть в пределах от 0,1 до 100 %!");
            //    return false;
            //}

        });

    });

</script>*@

SteelMeltingMixtureApp/Views/Home/Excel.cshtml
@model SteelMeltingMixtureApp.Models.InputDataModel

@{
    ViewBag.Title = "Excel";
}
@{ if (ViewBag.Result == "Невозможно сохранить файл")
    {
        <h2>@ViewBag.Result</h2>
    }
    else
    {
        <h2>Файл успешно сохранен!</h2>
    }
}

SteelMeltingMixtureApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}
<br />

<link rel="stylesheet" href="~/Content/css/bootstrap.css" />
<script src="~/Scripts/js/bootstrap.js"></script>