SteelMeltingMixtureApp/Controllers/ComponentsElementsController.cs
using SteelMeltingMixture.Domain;
using SteelMeltingMixtureApp.Infrastructure;
using SteelMeltingMixtureApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SteelMeltingMixtureApp.Controllers
{
    [Authorize] // К контроллеру получают доступ только аутентифицированные пользователи.
    public class ComponentsElementsController : Controller
    {
        // Dependency Injection
        // Данные поля будут хранит ссылки на реальные репозитории или на тестовые в соответствии с параметрами переданными в конструктор
        IComponentsElementsRepository _componentsElements;
        IComponentsRepository _components;
        IElementsRepository _elements;
        IVariantsRepository _variants;
        IUserProfileRepository _users;

        public ComponentsElementsController()
            : this(new DALContext())
        {
        }

        public ComponentsElementsController(IDALContext context)
        {
            _componentsElements = context.ComponentsElements;
            _components = context.Components;
            _elements = context.Elements;
            _variants = context.Variants;
            _users = context.Users;
        }

        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "ClearTable")]
        public ActionResult Index(Object sender)
        {
            SteelMeltingMixtureDatabase _database = new SteelMeltingMixtureDatabase();
            _database.ComponentsElements.RemoveRange(_database.ComponentsElements.Where(o => o.Owner.ID_User == _users.CurrentUser.ID_User));
            _database.SaveChanges();

            return RedirectToAction("Index");
        }


        [HttpPost]
        [MultiButton(MatchFormKey = "action", MatchFormValue = "LoadTable")]
        public ActionResult Index(ComponentsElements componentsElements)
        {
            #region --- Ввод тестовых данных в базу данных

            // компонент 1 - "Чугун литейный хромоникелевый"
            ComponentsElements val_11 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный хромоникелевый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element  = _elements.All.First(p => p.NameElement == "Si" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 2.95,                
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_11);
            _componentsElements.Save();

            ComponentsElements val_12 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный хромоникелевый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Mn" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 0.55,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_12);
            _componentsElements.Save();

            ComponentsElements val_13 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный хромоникелевый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Cr" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 2.45,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_13);
            _componentsElements.Save();

            ComponentsElements val_14 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный хромоникелевый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Ni" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 1.20,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_14);
            _componentsElements.Save();


            // компонент 2 - "Чугун литейный коксовый"
            ComponentsElements val_21 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный коксовый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Si" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 3.64,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_21);
            _componentsElements.Save();

            ComponentsElements val_22 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный коксовый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Mn" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 0.78,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_22);
            _componentsElements.Save();

            ComponentsElements val_23 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный коксовый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Cr" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 0.0,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_23);
            _componentsElements.Save();

            ComponentsElements val_24 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун литейный коксовый" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Ni" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 0.0,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_24);
            _componentsElements.Save();

            // компонент 3 - "Чугун зеркальный"
            ComponentsElements val_31 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун зеркальный" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Si" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 2.00,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_31);
            _componentsElements.Save();

            ComponentsElements val_32 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун зеркальный" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Mn" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,
                ID_Variant = _variants.All.First(p => p.NameVariant == "Вариант 1" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Variant,
                Val = 23.4,
                IsSolve = true,
                Owner = _users.CurrentUser
            };
            _componentsElements.InsertOrUpdate(val_32);
            _componentsElements.Save();

            ComponentsElements val_33 = new ComponentsElements
            {
                ID_Component = _components.All.First(p => p.NameComponent == "Чугун зеркальный" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Component,
                ID_Element = _elements.All.First(p => p.NameElement == "Cr" && p.Owner.ID_User == _users.CurrentUser.ID_User).ID_Element,

SteelMeltingMixtureApp/Views/ComponentsElements/Create.cshtml
@model SteelMeltingMixture.Domain.ComponentsElements

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ComponentsElements</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_Component, "ID_Component", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Component", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Component, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Element, "ID_Element", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Element", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Element, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Variant, "ID_Variant", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Variant", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Variant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Val, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Val, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Val, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSolve, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSolve)
                    @Html.ValidationMessageFor(model => model.IsSolve, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SteelMeltingMixtureApp/Views/ComponentsElements/Delete.cshtml
@model SteelMeltingMixture.Domain.ComponentsElements

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ComponentsElements</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Components.NameComponent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Components.NameComponent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Elements.NameElement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Elements.NameElement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Variants.NameVariant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Variants.NameVariant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Val)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Val)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSolve)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSolve)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SteelMeltingMixtureApp/Views/ComponentsElements/Details.cshtml
@model SteelMeltingMixture.Domain.ComponentsElements

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ComponentsElements</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Components.NameComponent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Components.NameComponent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Elements.NameElement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Elements.NameElement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Variants.NameVariant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Variants.NameVariant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Val)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Val)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsSolve)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsSolve)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_ComponentElements }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SteelMeltingMixtureApp/Views/ComponentsElements/Edit.cshtml
@model SteelMeltingMixture.Domain.ComponentsElements

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ComponentsElements</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_ComponentElements)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Component, "ID_Component", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Component", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Component, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Element, "ID_Element", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Element", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Element, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Variant, "ID_Variant", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Variant", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Variant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Val, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Val, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Val, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsSolve, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsSolve)
                    @Html.ValidationMessageFor(model => model.IsSolve, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SteelMeltingMixtureApp/Views/ComponentsElements/Index.cshtml
@model IEnumerable<SteelMeltingMixture.Domain.ComponentsElements>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "ComponentsElements", FormMethod.Post))
{
    <button type="submit" name="action" value="ClearTable">Очистить таблицу</button>
    <button type="submit" name="action" value="LoadTable">Заполнить таблицу</button>
    <p>
    </p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <form method="post">
        <div class=" form-inline">
            <label class=" control-label">Варианты расчета: </label>
            @Html.DropDownList("ID_Variant", null, "Все",
                  htmlAttributes: new { @class = "form-control" })

            <input type="submit" value="Фильтр" class=" btn btn-default" />
        </div>
    </form>
}*@

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Components.NameComponent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Elements.NameElement)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Variants.NameVariant)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Val)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsSolve)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Components.NameComponent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Elements.NameElement)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Variants.NameVariant)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Val)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsSolve)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID_ComponentElements }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID_ComponentElements }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID_ComponentElements })
            </td>
        </tr>
    }

</table>